//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noriam.SOLID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_USUARIO()
        {
            this.CAT_PRECIO = new HashSet<CAT_PRECIO>();
            this.CAT_PRODUCTO = new HashSet<CAT_PRODUCTO>();
            this.MOVIMIENTO_PRODUCTO = new HashSet<MOVIMIENTO_PRODUCTO>();
        }
    
        public int ID_CAT_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENIA { get; set; }
        public int ID_CAT_ROL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_PRECIO> CAT_PRECIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_PRODUCTO> CAT_PRODUCTO { get; set; }
        public virtual CAT_ROL CAT_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTO_PRODUCTO> MOVIMIENTO_PRODUCTO { get; set; }
    }
}
