//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noriam.SOLID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_PRODUCTO()
        {
            this.CAT_PRECIO = new HashSet<CAT_PRECIO>();
            this.MOVIMIENTO_PRODUCTO = new HashSet<MOVIMIENTO_PRODUCTO>();
        }
    
        public int ID_CAT_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public string MARCA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> EXISTENCIA { get; set; }
        public int CREADO_POR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_PRECIO> CAT_PRECIO { get; set; }
        public virtual CAT_USUARIO CAT_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTO_PRODUCTO> MOVIMIENTO_PRODUCTO { get; set; }
    }
}
