//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noriam.SOLID.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABC_SOLIDEntities : DbContext
    {
        public ABC_SOLIDEntities()
            : base("name=ABC_SOLIDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_PRECIO> CAT_PRECIO { get; set; }
        public virtual DbSet<CAT_PRODUCTO> CAT_PRODUCTO { get; set; }
        public virtual DbSet<CAT_ROL> CAT_ROL { get; set; }
        public virtual DbSet<CAT_USUARIO> CAT_USUARIO { get; set; }
        public virtual DbSet<MOVIMIENTO_PRODUCTO> MOVIMIENTO_PRODUCTO { get; set; }
    }
}
